/**
 * 🎬 EGAP Executive Demo — Phase 5 End-to-End Scenario
 *
 * Demonstrates the full lifecycle: Webhook → Ingress → Pub/Sub → Orchestrator → HITL Task
 */

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const INGRESS_URL = 'https://egap-ingress-910005263485.us-central1.run.app';
const REPO_NAME = 'egap-core-demo';
const MAX_POLLS = 10;
const POLL_MS = 2000;

// ─── Helpers ──────────────────────────────────────────────────────────────────
function timestamp(): string {
    return new Date().toISOString().replace('T', ' ').slice(0, 19);
}

function sleep(ms: number): Promise<void> {
    return new Promise(r => setTimeout(r, ms));
}

function divider(): void {
    console.log('──────────────────────────────────────────────────');
}

// ─── Step 1: The Trigger (Ingress) ────────────────────────────────────────────
async function sendWebhook(): Promise<{ traceId?: string }> {
    console.log('\n🚀 Sending simulated GitHub Webhook...');
    divider();

    const payload = {
        source: 'github',
        payload: { event: 'push', repo: REPO_NAME },
    };

    console.log(`   Target:  ${INGRESS_URL}/webhook`);
    console.log(`   Payload: ${JSON.stringify(payload)}`);
    console.log();

    const res = await fetch(`${INGRESS_URL}/webhook`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
    });

    if (!res.ok) {
        const text = await res.text();
        throw new Error(`Ingress returned ${res.status}: ${text}`);
    }

    const data = (await res.json()) as Record<string, unknown>;
    console.log(`   ✅ Ingress Response: ${res.status} OK`);
    console.log(`   📨 Message ID:      ${data.messageId ?? 'N/A'}`);

    return { traceId: (data.traceId as string) ?? undefined };
}

// ─── Step 2: The Verification (Orchestration) ────────────────────────────────
async function pollForTask(): Promise<{
    id: string;
    description: string;
    status: string;
    createdAt: Date;
    agent: { id: string; name: string; role: string } | null;
}> {
    console.log('\n⏳ Polling for orchestrated task...');
    divider();

    for (let i = 1; i <= MAX_POLLS; i++) {
        console.log(`   Poll ${i}/${MAX_POLLS} — checking Task table...`);

        const task = await prisma.task.findFirst({
            where: {
                status: 'PENDING',
                description: { contains: REPO_NAME },
            },
            orderBy: { createdAt: 'desc' },
            include: { agent: { select: { id: true, name: true, role: true } } },
        });

        if (task) {
            console.log(`   ✅ Task found!`);
            return task;
        }

        await sleep(POLL_MS);
    }

    throw new Error(
        `No task containing "${REPO_NAME}" appeared after ${MAX_POLLS * POLL_MS / 1000}s. ` +
        `Is the Orchestrator running and subscribed to egap-ingress-sub?`
    );
}

// ─── Step 3: The Reconciliation (Executive Report) ───────────────────────────
function printReport(
    task: Awaited<ReturnType<typeof pollForTask>>,
    traceId?: string,
): void {
    console.log('\n');
    console.log('📊 EGAP LIVE DEMO REPORT');
    divider();
    console.log(`✅ Signal Received:   ${timestamp()}`);
    console.log(`✅ Trace ID:          ${traceId ?? '(generated by ingress)'}`);
    console.log(`✅ Agent Activated:   ${task.agent?.name ?? 'Unknown'} (Role: ${task.agent?.role ?? 'N/A'})`);
    console.log(`✅ Task Created:      ${task.id}`);
    console.log(`⚠️  Status:            ${task.status} (HITL Gate Active)`);
    divider();
    console.log('🎯 DEMO SUCCESSFUL: Nervous System is operational.');
    console.log();
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
    console.log();
    console.log('╔══════════════════════════════════════════════════╗');
    console.log('║        🛸 EGAP EXECUTIVE DEMO — Phase 5         ║');
    console.log('╚══════════════════════════════════════════════════╝');

    try {
        // Step 1 — fire webhook at the live Cloud Run ingress
        const { traceId } = await sendWebhook();

        // Step 2 — poll the local DB for the orchestrated task
        const task = await pollForTask();

        // Step 3 — print executive‑style report
        printReport(task, traceId);
    } catch (err: unknown) {
        console.error('\n❌ Demo failed:', (err as Error).message);
        console.log('\n💡 Troubleshooting:');
        console.log('   1. Is the Cloud SQL proxy running?  ./cloud-sql-proxy ...');
        console.log('   2. Is the Orchestrator running?     cd egap-factory/services/orchestrator && npx ts-node src/server.ts');
        console.log('   3. Is the Ingress URL reachable?    curl ' + INGRESS_URL + '/health');
        process.exit(1);
    } finally {
        await prisma.$disconnect();
    }
}

main();
